// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":false,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"816","changeWindowHeightTo":"624","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Tekoki_Miscs","status":true,"description":"","parameters":{}},
{"name":"TitleCommandPosition","status":false,"description":"Changes the position of the title command window.","parameters":{"Offset X":"0","Offset Y":"0","Width":"240","Background":"0"}},
{"name":"Drill_LayerCamera","status":true,"description":"[v1.6]        地图 - 活动地图镜头","parameters":{"缩小镜头时是否加强刷新量":"true","镜头移动模式":"弹性移动","弹性模式移动速度":"14","弹性模式镜头速度上限":"24"}}
];
